# Q1. What is a database? Differentiate between SQL and NoSQL databases.

### ans

A database is a structured collection of data that is organized in a way that allows for efficient storage, retrieval, and manipulation of information. It acts as a centralized repository where data can be stored, managed, and accessed by software applications or users.

The difference between SQL and NoSQL databases are:

#### 1. Data Structure:
  * SQL Databases:
    * SQL databases are also known as relational databases.
    * They are based on a predefined schema, which means the structure of the data (tables, columns, relationships) is fixed before the data is added.
    * Data is organized in tables with predefined columns.

  * NoSQL Databases:
    * NoSQL databases do not require a fixed schema.
    * They can be document-oriented, key-value stores, wide-column stores, or graph databases.
    * Data can be stored in various formats like JSON, BSON, XML, etc.

#### 2. Relational vs. Non-Relational:
  * SQL Databases:
    * SQL databases use a structure that allows you to define relationships between different pieces of data.
    * They are based on the relational model and follow ACID (Atomicity, Consistency, Isolation, Durability) properties.

  * NoSQL Databases:
    * NoSQL databases do not rely on a fixed schema or predefined relationships.
    * They may be non-relational or loosely relational, and they often follow the CAP (Consistency, Availability, Partition tolerance) theorem.

#### 3. Scalability:
  * SQL Databases:
    * Traditionally, SQL databases have faced challenges with horizontal scalability, which means it can be more difficult to scale them across multiple servers.

  * NoSQL Databases:
    * NoSQL databases are designed to scale horizontally, making them more suitable for handling large amounts of data across multiple servers.

#### 4. Use Cases:
  * SQL Databases:
    * Well-suited for applications that require complex query operations, transactions, and where data integrity and consistency are critical.
    * Commonly used in applications like financial systems, e-commerce platforms, and applications with complex reporting.

  * NoSQL Databases:
    * Often used in scenarios where high throughput, scalability, and flexibility in data modeling are crucial.
    * Commonly employed in applications like real-time analytics, content management systems, and large-scale web applications.

#### 5. Examples:
  * SQL Databases:
    * MySQL, PostgreSQL, Oracle, Microsoft SQL Server, SQLite.

  * NoSQL Databases:
    * MongoDB, Cassandra, Couchbase, Redis, Neo4j.

# Q2. What is DDL? Explain why CREATE, DROP, ALTER, and TRUNCATE are used with an example.

### ans

Data Definition Language(DDL) is a category of SQL commands that are used to define, modify, and manage the structure of a database and its objects. DDL commands are used to create, alter, and drop database objects like tables, indexes, views, and schemas.

Some common DDL commands are:

### CREATE:
* The CREATE command is used to create new database objects, such as tables, indexes, views, or databases.
  * Example (creating a table):
    * CREATE TABLE customers (id INT PRIMARY KEY, first_name VARCHAR(50), last_name VARCHAR(50), email VARCHAR(100));

### DROP:
* The DROP command is used to delete existing database objects, such as tables, indexes, views, or databases.
  * Example (dropping a table):
    * DROP TABLE customers;

### ALTER:
* The ALTER command is used to modify existing database objects, such as adding or deleting columns in a table, renaming objects, or modifying data types.
  * Example (adding a column to a table):
    * ALTER TABLE customers ADD phone_number VARCHAR(20);
    
### TRUNCATE:
* The TRUNCATE command is used to remove all records from a table, but it retains the structure of the table for future use.
  * Example (truncating a table):
    * TRUNCATE TABLE customers;

# Q3. What is DML? Explain INSERT, UPDATE, and DELETE with an example.

### ans

Data Manipulation Language(DML) is a category of SQL commands used to interact with and manipulate data within a database. DML commands include operations like inserting new records, updating existing records, and deleting records.

The main DML commands are:

### INSERT:
* The INSERT command is used to add new records (rows) into a table.
  * Example (inserting a new record):
    * INSERT INTO customers (first_name, last_name, email) VALUES ('John', 'Doe', 'john.doe@example.com');
    
### UPDATE:
* The UPDATE command is used to modify existing records in a table.
  * Example (updating a record):
    * UPDATE customers SET email = 'john.doe@newemail.com' WHERE id = 1;
    
### DELETE:
* The DELETE command is used to remove records from a table.
  * Example (deleting a record):
    * DELETE FROM customers WHERE id = 2;

# Q4. What is DQL? Explain SELECT with an example.

### ans

Data Query Language(DQL) is a category of SQL commands that are used to retrieve and manipulate data from a database. DQL specifically focuses on the querying aspect, allowing users to retrieve information from tables in a database.

### SELECT:
* The SELECT statement is used to retrieve data from one or more tables. It allows us to specify the columns you want to retrieve and apply various filtering and sorting criteria.

  * Example of a SELECT statement are:
    * SELECT column1, column2, ... FROM table_name;
    
  * If we have a table named students with columns student_id, first_name, last_name, and age, we can use a SELECT statement to retrieve specific information.
    
    * SELECT first_name, last_name, age FROM students;

# Q5. Explain Primary Key and Foreign Key.

### ans

### Primary Key:
A primary key is a special field or combination of fields in a database table that uniquely identifies each record (row) in the table. It serves as a reference point for establishing relationships between different tables in a database. 

* Some important points about primary keys are:

  * Uniqueness: Each value in a primary key column must be unique. This ensures that no two records in the table can have the same primary key value.

  * Non-null: A primary key field cannot contain null values. Every record must have a valid, non-null value in the primary key column.

  * Immutable: Ideally, the values in a primary key should be immutable, meaning they should not change over time. This helps maintain data integrity.

  * Single Field or Composite Key: A primary key can be a single field or a combination of multiple fields that, when combined, form a unique identifier.

  * Indexed: In most database systems, a primary key is automatically indexed. This improves query performance when searching for specific records.

Example: In a table of students, a primary key could be the student ID, as each student would have a unique ID number.

### Foreign Key:
A foreign key is a field in a database table that refers to the primary key in another table. It establishes a relationship between two tables by linking a field in one table to a field in another.

* Some important points about foreign keys are:

  * Referential Integrity: A foreign key enforces referential integrity by ensuring that the values in the foreign key column match values in the corresponding primary key column of the referenced table.

  * Relationships: Foreign keys are used to define relationships between tables. 
  
    For example, in a database with separate tables for customers and orders, a foreign key in the orders table might reference the customer ID in the customers table.

  * Can Contain Null Values: Unlike a primary key, a foreign key can contain null values. This allows for optional relationships.

Example: In an orders table, a foreign key might reference the customer ID in a customers table. This establishes a relationship between orders and customers, indicating which customer placed each order.

# Q6. Write a python code to connect MySQL to python. Explain the cursor() and execute() method.

### ans

The python code to connect MySQL to python are:

In [ ]:
import mysql.connector

# Establishing a connection
conn = mysql.connector.connect(
    host="localhost",
    user="abc",
    password="pwskills",
    database="data science")

# Creating a cursor
cursor = conn.cursor()

# Executing a query
cursor.execute("SELECT * FROM database")

# Fetching results
results = cursor.fetchall()

# Displaying results
for i in results:
    print(i)

# Closing the cursor and connection
cursor.close()
conn.close()

### Explanation:

1. Importing the mysql.connector Module:
* The first step is to import the mysql.connector module, which provides the necessary functions and classes to connect to MySQL databases.

2. Establishing a Connection:
* mysql.connector.connect() is used to create a connection to the MySQL server. we'll need to provide the host, user, password, and the name of the database we want to connect to.

3. Creating a Cursor:
* A cursor is an object that allows us to execute SQL queries and fetch results. It acts as a pointer to a specific location within a dataset. cursor() is a method of the connection object that creates a new cursor.

4. Executing a Query:
* cursor.execute() is used to execute an SQL query. In this example, we're executing a simple SELECT query, but we can use any valid SQL statement.

5. Fetching Results:
* After executing a query, we can use cursor.fetchall() to retrieve the results. This method returns a list of tuples, where each tuple represents a row in the result set.

6. Displaying Results:
* In this example, we're iterating through the results and printing each row.

7. Closing Cursor and Connection:
* It's important to close the cursor and connection once we're done using them. This releases any resources held by them.

## The Explanation of cursor() and execute() methods are:

### cursor() Method:
 * cursor() is a method of the connection object. It creates a new cursor that allows us to execute SQL queries and retrieve results.


### execute() Method:
 * execute() is a method of the cursor object. It is used to execute an SQL query. we pass the query as a string to this method. If the query is a SELECT statement, it fetches the result set. For other queries like INSERT, UPDATE, or DELETE, it performs the operation on the database.

# Q7. Give the order of execution of SQL clauses in an SQL query.

### ans

The order of execution of SQL clauses in an SQL query as follows:

1. FROM: Specifies the tables or views from which the data will be retrieved.

2. JOIN: Combines rows from different tables based on a related column between them. This can include INNER JOIN, LEFT JOIN, RIGHT JOIN, and other types of joins.

3. WHERE: Filters the rows based on a specified condition or set of conditions.

4. GROUP BY: Groups the result set by one or more columns, often used in conjunction with aggregate functions like COUNT, SUM, AVG, etc.

5. HAVING: Applies a condition to the result set after it has been grouped by the GROUP BY clause.

6. SELECT: Specifies which columns or expressions will be included in the result set.

7. DISTINCT: Filters out duplicate rows from the result set.

8. ORDER BY: Sorts the result set based on one or more columns, in ascending or descending order.

9. LIMIT / OFFSET (or FETCH / OFFSET in some databases): Limits the number of rows returned in the result set and allows for pagination.

10. UNION / INTERSECT / EXCEPT: Combines the result sets of multiple SELECT queries.